"use client";

import { useState, useMemo } from "react";
import { Send, CheckCircle2, Sparkles, FileText, SendHorizontal, Loader2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { mockResults, mockStudents, mockCycles } from "@/lib/mock-data";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/lib/auth-context";
import { api } from "@/lib/api-client";
import { shouldUseRealAPI } from "@/lib/api-config";

const COMPETENCIES = [
  "Structural",
  "Civil",
  "Electrical",
  "Mechanical",
  "Software",
];
const CLASSES = ["Junior", "Wheeler", "Senior", "Lead"];

export default function VerifierReportPage() {
  const { toast } = useToast();
  const { user } = useAuth();
  const activeCycle = mockCycles.find((c) => c.status === "active");

  const [notes, setNotes] = useState("");
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);

  const allResults = useMemo(
    () => mockResults.filter((r) => r.status !== "draft"),
    [],
  );

  const byCompetency = useMemo(
    () =>
      COMPETENCIES.map((comp) => {
        const compResults = allResults.filter((r) => r.competency === comp);
        return {
          comp,
          total: compResults.length,
          approved: compResults.filter((r) => r.status === "approved").length,
          submitted: compResults.filter((r) => r.status === "submitted").length,
        };
      }).filter((c) => c.total > 0),
    [allResults],
  );

  const byClass = useMemo(
    () =>
      CLASSES.map((cls) => {
        const classStudents = mockStudents.filter((s) => s.gradeLevel === cls);
        const classResults = allResults.filter((r) =>
          classStudents.some((s) => s.id === r.studentId),
        );
        return {
          cls,
          students: classStudents.length,
          assessed: classResults.length,
          approved: classResults.filter((r) => r.status === "approved").length,
        };
      }).filter((c) => c.students > 0),
    [allResults],
  );

  const handleSend = async () => {
    if (!notes.trim()) {
      toast({
        title: "Notes Required",
        description: "Please summarize monitoring observations before transmitting.",
        variant: "destructive",
      });
      return;
    }

    if (!shouldUseRealAPI()) {
      setSent(true);
      toast({
        title: "Report Dispatched",
        description: "Your verification report has been transmitted to Academic Control.",
      });
      return;
    }

    setLoading(true);
    try {
      let content = `Monitoring Report for ${activeCycle?.name || "Current Cycle"}\n\n`;
      content += `Generated by: ${user?.fullName || "Verifier"}\n\n`;
      content += `PROGRESS BY COMPETENCY:\n`;
      byCompetency.forEach((c) => {
        content += `- ${c.comp}: ${c.approved}/${c.total} approved (${c.submitted} pending)\n`;
      });
      content += `\nPROGRESS BY CLASS:\n`;
      byClass.forEach((c) => {
        content += `- ${c.cls}: ${c.assessed}/${c.students} assessed, ${c.approved} approved\n`;
      });
      content += `\nNOTES:\n${notes}\n`;

      await api.reports.createControllerReport({
        cycleId: Number(activeCycle?.id) || 1,
        reportType: "Verifier Monitoring",
        title: `Monitoring Report - ${activeCycle?.name || "Cycle"}`,
        content: content,
        generatedBy: user?.accountId ? Number(user.accountId) : undefined,
      });

      await api.reports.createActivityLog({
        userId: user?.accountId ? Number(user.accountId) : undefined,
        actionType: "Report Sent",
        entityType: "ControllerReport",
        entityId: activeCycle?.id ? Number(activeCycle.id) : undefined,
        newValue: `Verifier sent monitoring report for ${activeCycle?.name}`,
      });

      setSent(true);
      toast({
        title: "Report Transmitted",
        description: "Your monitoring report has been logged and sent to Controller.",
      });
    } catch (error) {
      toast({
        title: "Transmission Failed",
        description: "Failed to dispatch report. Please retry.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 sm:space-y-8 animate-in fade-in-50 duration-300">
      {/* Executive Hero Banner */}
      <div className="p-6 sm:p-8 rounded-3xl bg-gradient-to-br from-slate-900 via-slate-900 to-[#1b0d10] text-white border border-slate-800 shadow-xl relative overflow-hidden">
        {/* Glow effects */}
        <div className="absolute -top-24 -right-24 w-80 h-80 rounded-full bg-[#c8102e]/25 blur-[100px] pointer-events-none" />
        <div className="absolute -bottom-24 left-1/4 w-64 h-64 rounded-full bg-[#e8192f]/15 blur-[90px] pointer-events-none" />

        <div className="relative z-10 flex flex-col sm:flex-row sm:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-[#c8102e]/20 text-[#ff4d6a] border border-[#c8102e]/40 shadow-sm">
                <Sparkles className="w-3.5 h-3.5" />
                Audit Reporting
              </span>
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-white/10 text-white/90 border border-white/15">
                <FileText className="w-3.5 h-3.5" />
                Executive Summary
              </span>
            </div>

            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white">
              QA Report to Controller
            </h1>
            <p className="text-slate-300 text-xs sm:text-sm max-w-2xl leading-relaxed">
              Consolidate cycle observations, highlight discrepancies, and
              formally transmit verification sign-offs to Academic Control.
            </p>
          </div>

          <div className="bg-white/5 backdrop-blur-md px-5 py-3.5 rounded-2xl border border-white/10 text-center shrink-0">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-300 block">
              Active Cycle
            </span>
            <span className="text-base font-extrabold text-white block mt-0.5">
              {activeCycle ? activeCycle.name : "Current Round"}
            </span>
          </div>
        </div>
      </div>

      {/* Progress Cards Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Competency Audit Progress */}
        <Card className="p-6 rounded-3xl bg-white dark:bg-[#121218] border border-slate-200/80 dark:border-white/10 shadow-sm">
          <h2 className="text-base font-bold text-slate-900 dark:text-white mb-4">
            Progress by Technical Competency
          </h2>
          <div className="space-y-4">
            {byCompetency.length === 0 ? (
              <p className="text-xs text-slate-400 dark:text-neutral-500 py-6 text-center">
                No submitted assessment data available.
              </p>
            ) : (
              byCompetency.map((c) => {
                const percent =
                  c.total > 0 ? Math.round((c.approved / c.total) * 100) : 0;
                return (
                  <div
                    key={c.comp}
                    className="p-3.5 rounded-2xl bg-slate-50 dark:bg-white/[0.02] border border-slate-100 dark:border-white/5"
                  >
                    <div className="flex items-center justify-between text-xs mb-2">
                      <span className="font-bold text-slate-800 dark:text-neutral-200">
                        {c.comp}
                      </span>
                      <span className="text-slate-500 dark:text-neutral-400 font-medium">
                        <span className="text-emerald-600 dark:text-emerald-400 font-bold">
                          {c.approved}
                        </span>{" "}
                        approved · {c.submitted} pending
                      </span>
                    </div>
                    <div className="w-full bg-slate-200 dark:bg-white/10 rounded-full h-2 overflow-hidden">
                      <div
                        className="bg-gradient-to-r from-emerald-500 to-teal-500 h-2 rounded-full transition-all"
                        style={{ width: `${percent}%` }}
                      />
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </Card>

        {/* Cohort Progress */}
        <Card className="p-6 rounded-3xl bg-white dark:bg-[#121218] border border-slate-200/80 dark:border-white/10 shadow-sm">
          <h2 className="text-base font-bold text-slate-900 dark:text-white mb-4">
            Progress by Class Cohort
          </h2>
          <div className="grid grid-cols-2 gap-3">
            {byClass.map((c) => (
              <div
                key={c.cls}
                className="p-4 rounded-2xl bg-slate-50 dark:bg-white/[0.02] border border-slate-100 dark:border-white/5 text-center"
              >
                <span className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-neutral-400 block">
                  {c.cls}
                </span>
                <span className="text-3xl font-extrabold text-[#c8102e] dark:text-[#ff4d6a] block my-1">
                  {c.assessed}
                </span>
                <span className="text-[11px] text-slate-400 dark:text-neutral-500 block">
                  of {c.students} assessed
                </span>
                <span className="inline-block mt-2 text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-900/30">
                  {c.approved} Approved
                </span>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* Report Notes & Transmit Card */}
      <Card className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-[#121218] border border-slate-200/80 dark:border-white/10 shadow-sm">
        <h2 className="text-base font-bold text-slate-900 dark:text-white mb-1">
          Verifier Audit Notes & Recommendations
        </h2>
        <p className="text-xs text-slate-500 dark:text-neutral-400 mb-4">
          Detail any grading anomalies, exceptional achievements, or re-test
          mandates for Academic Control review.
        </p>

        <Textarea
          placeholder="e.g. Assessment across technical competencies is consistent. 2 re-trials in Electrical require attention before final graduation sign-off..."
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          rows={5}
          disabled={sent}
          className="rounded-2xl resize-none text-xs sm:text-sm bg-slate-50 dark:bg-[#16161f] border-slate-200/80 dark:border-white/10"
        />

        <div className="mt-6 flex justify-end">
          {sent ? (
            <div className="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-900/30 text-emerald-700 dark:text-emerald-400 text-xs font-bold uppercase tracking-wider">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              Report Dispatched to Academic Control
            </div>
          ) : (
            <Button
              onClick={handleSend}
              disabled={loading}
              className="rounded-xl px-6 py-5 bg-[#c8102e] hover:bg-[#b00d27] text-white font-bold shadow-md shadow-[#c8102e]/20"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Transmitting Report...
                </>
              ) : (
                <>
                  <SendHorizontal className="w-4 h-4 mr-2" />
                  Dispatch Report to Controller
                </>
              )}
            </Button>
          )}
        </div>
      </Card>
    </div>
  );
}
