"use client";

import { useState, useMemo } from "react";
import { Send, CheckCircle2, Sparkles, FileText, SendHorizontal, Loader2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/lib/auth-context";
import { api } from "@/lib/api-client";
import { useApiQuery } from "@/hooks/use-api";

export default function VerifierReportPage() {
  const { toast } = useToast();
  const { user } = useAuth();

  const [notes, setNotes] = useState("");
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);

  // Load real courses from API
  const { data: courses } = useApiQuery(() => api.courses.getAll(), []);
  // Load real rounds from API
  const { data: rounds } = useApiQuery(() => api.courseRounds.getAll(), []);
  // Load real results from API
  const { data: results } = useApiQuery(() => api.competencyResults.getAll(), []);

  const activeRound = useMemo(() => {
    return rounds?.find((r) => r.statusId === 1) || rounds?.[0];
  }, [rounds]);

  const byCourse = useMemo(() => {
    if (!courses || !results) return [];
    return courses.map((course) => {
      const courseResults = results.filter((r) => r.courseId === course.id);
      return {
        title: course.title,
        total: courseResults.length,
        passed: courseResults.filter((r) => r.resultStatusId === 53).length,
      };
    });
  }, [courses, results]);

  const handleSend = async () => {
    if (!notes.trim()) {
      toast({
        title: "Notes Required",
        description: "Please summarize monitoring observations before transmitting.",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      let content = `Monitoring Report for Round ${activeRound?.roundNumber || "Active"}\n\n`;
      content += `Generated by: ${user?.fullName || "Verifier"}\n\n`;
      content += `PROGRESS BY COURSE/COMPETENCY:\n`;
      byCourse.forEach((c) => {
        content += `- ${c.title}: ${c.passed}/${c.total} passed\n`;
      });
      content += `\nNOTES:\n${notes}\n`;

      await api.reports.createControllerReport({
        cycleId: activeRound?.id ? Number(activeRound.id) : 1,
        reportType: "Verifier Monitoring",
        title: `Monitoring Report - Round ${activeRound?.roundNumber || "1"}`,
        content: content,
        generatedBy: user?.accountId ? Number(user.accountId) : undefined,
      });

      await api.reports.createActivityLog({
        userId: user?.accountId ? Number(user.accountId) : undefined,
        actionType: "Report Sent",
        entityType: "ControllerReport",
        entityId: activeRound?.id ? Number(activeRound.id) : undefined,
        newValue: `Verifier sent monitoring report for Round ${activeRound?.roundNumber || "1"}`,
      });

      setSent(true);
      toast({
        title: "Report Transmitted",
        description: "Your monitoring report has been logged and sent to Controller.",
      });
    } catch (error) {
      toast({
        title: "Transmission Failed",
        description: "Failed to dispatch report. Please retry.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 sm:space-y-8 animate-in fade-in-50 duration-300">
      {/* Executive Hero Banner */}
      <div className="p-6 sm:p-8 rounded-3xl bg-gradient-to-br from-slate-900 via-slate-900 to-[#1b0d10] text-white border border-slate-800 shadow-xl relative overflow-hidden">
        {/* Glow effects */}
        <div className="absolute -top-24 -right-24 w-80 h-80 rounded-full bg-[#c8102e]/25 blur-[100px] pointer-events-none" />
        <div className="absolute -bottom-24 left-1/4 w-64 h-64 rounded-full bg-[#e8192f]/15 blur-[90px] pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-[#c8102e]/20 text-[#ff4d6a] border border-[#c8102e]/40 shadow-sm">
                <Sparkles className="w-3.5 h-3.5" />
                Executive Reporting
              </span>
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-white/10 text-white/90 border border-white/15">
                <FileText className="w-3.5 h-3.5" />
                Round {activeRound?.roundNumber || "1"}
              </span>
            </div>

            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white">
              Academic Verification Dispatch
            </h1>
            <p className="text-slate-300 text-xs sm:text-sm max-w-2xl leading-relaxed">
              Consolidate cycle monitoring observations, quality compliance, and submit the
              formal audit summary directly to Academic Control.
            </p>
          </div>

          <div className="bg-white/5 backdrop-blur-md px-5 py-3.5 rounded-2xl border border-white/10 text-center shrink-0">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-300 block">
              Active Cycle
            </span>
            <span className="text-sm font-extrabold text-white block mt-0.5">
              Round {activeRound?.roundNumber || "1"}
            </span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 sm:gap-8">
        {/* Progress Breakdown */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="p-6 rounded-3xl bg-white dark:bg-[#121218] border border-slate-200/80 dark:border-white/10 shadow-sm">
            <h2 className="font-extrabold text-slate-900 dark:text-white text-base mb-4">
              Competencies Monitored
            </h2>
            <div className="space-y-3">
              {byCourse.map((c) => (
                <div
                  key={c.title}
                  className="p-3.5 rounded-2xl bg-slate-50 dark:bg-white/[0.03] border border-slate-100 dark:border-white/5 flex items-center justify-between"
                >
                  <div>
                    <p className="font-bold text-xs text-slate-800 dark:text-neutral-200">
                      {c.title}
                    </p>
                    <p className="text-[11px] text-slate-400 dark:text-neutral-500">
                      {c.passed} / {c.total} passed
                    </p>
                  </div>
                  <span className="text-xs font-mono font-extrabold text-[#c8102e] dark:text-[#ff4d6a]">
                    {c.total > 0 ? Math.round((c.passed / c.total) * 100) : 0}%
                  </span>
                </div>
              ))}
              {byCourse.length === 0 && (
                <p className="text-xs text-slate-400">Loading course breakdown...</p>
              )}
            </div>
          </Card>
        </div>

        {/* Report Editor */}
        <div className="lg:col-span-2">
          <Card className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-[#121218] border border-slate-200/80 dark:border-white/10 shadow-sm space-y-6">
            <div>
              <h2 className="font-extrabold text-slate-900 dark:text-white text-lg">
                Official Verification Notes
              </h2>
              <p className="text-xs text-slate-500 dark:text-neutral-400 mt-1">
                Enter qualitative observations, assessment variance notes, or procedural flags.
              </p>
            </div>

            <Textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Record audit observations, verification anomalies, assessor consistency findings, or general cycle feedback..."
              disabled={sent || loading}
              rows={8}
              className="resize-none rounded-2xl text-sm"
            />

            <div className="pt-2 flex items-center justify-between flex-wrap gap-4">
              <span className="text-xs text-slate-400 dark:text-neutral-500">
                Transmitted records are archived to the immutable audit log.
              </span>

              {sent ? (
                <div className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400 font-bold text-xs">
                  <CheckCircle2 className="w-4 h-4" />
                  Report Transmitted Successfully
                </div>
              ) : (
                <Button
                  onClick={handleSend}
                  disabled={loading || !notes.trim()}
                  className="rounded-xl px-6 font-bold shadow-lg shadow-[#c8102e]/20"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Transmitting...
                    </>
                  ) : (
                    <>
                      <SendHorizontal className="w-4 h-4 mr-2" />
                      Transmit to Controller
                    </>
                  )}
                </Button>
              )}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
